#port number that microservice listens to
port: 3001
#redis related settings
# host: hostname:port
# password: password for AUTH command
redis:
  host: "192.168.99.100:6379"
  password: ""
#nsq related settings
# nsqlookupd-host: nsqlookupd host:port that listens to NATIVE clients
# topic: topic to find messages for the service
# channel: channel name assigned to service's consumer
# max-inflight: Maximum number of messages to allow in flight (concurrency knob)
# num-publishers: number of concurrent publishers
nsq:
  nsqlookupd-host: "192.168.99.100:4161"
  topic: "locations"
  channel: "driver-location-service"
  max-inflight: 200
  num-publishers: 100